### ISSUE TITLE
Stream mode does not work with img2img or txt2img with controlnet

### ISSUE THREAD

**Issue by xanderjm** [olegchomp/TDDiffusionAPI#11]
Having trouble with stream mode. It works fine on txt2img tab, but not at all on img2img - no errors in the SD terminal. 

It also stops working if i try add any controlNet units.

**Comment by olegchomp** [comment]
1) can you provide more information (what source for img2img, what resolution, parameters and etc) with `not at all on img2img - no errors in the SD terminal.`
2) also provide more information.

Just tested on my side and everything works
