### ISSUE TITLE
About AsyncIO implementations

### ISSUE THREAD

**Issue by state303** [olegchomp/TDDiffusionAPI#15]
First of all, thank you for the repo!

I am currently trying to implement asyncio with this repo, however, would like to know if you accepts any PR or such.
From what I can see is that all the requests are being handled synchronously, hence will block the main thread.
Awaiting for the reply... :)

Verdict: I don't know if the response status code 100 - related issues are fixed at this point, so maybe utilizing requests package will be a good alternative.

**Comment by olegchomp** [comment]
Hi! It works through [webclient](https://derivative.ca/UserGuide/TDResources) and it's async already (like [webclient DAT)](https://derivative.ca/UserGuide/Web_Client_DAT).  

Status code error is related to [this](https://forum.derivative.ca/t/tdresources-webclient-keyerror/398491). 

This repo is outdated and better to check [TDComfyUI](https://github.com/olegchomp/TDComfyUI). Here is already implemented some fixes and others improvements.

**Comment by state303** [comment]
Thanks a lot! I will checkout the repo.
