### ISSUE TITLE
Are "reference" preprocessors supported?

### ISSUE THREAD

**Issue by aulerius** [olegchomp/TDDiffusionAPI#3]
![image](https://github.com/olegchomp/TDDiffusionAPI/assets/51526300/7fd7c447-66e4-472f-ae14-b4635045abb6)

Recently added ["reference"](https://github.com/Mikubill/sd-webui-controlnet/discussions/1236) preprocessors work without a controlnet model. However in the parameter window of this component this is not reflected. After having done a few tests it appears the preprocessor is working despite that, so I suppose the ControlNet extension is ignoring the controlnet model under the hood, whatever happens to be selected at the time?
![image](https://github.com/olegchomp/TDDiffusionAPI/assets/51526300/a0f69343-5cd9-4c58-b52b-6d31313d5e20)

Additionally, the controlnet extension exposes a unique control for reference preprocessors called "style fidelity", seen in the first screenshot, which would be nice to expose in TD.

Cheers!
And thank you for this absolute gem. I've been looking for modular and temporal-conscious way of working with SD and this finally checks all the boxes! I'd be super into multi-controlnet support eventually, maybe with separate CN nodes with multi-node input?

**Comment by olegchomp** [comment]
Since TDA 2.0.7 controls auto-exposed in TD through ControlNet API and should appear everytime you swith preprocessor. As for reference_only, if it doesn't use model it might skip this parameter even if selected in TDA.
Multi-controlnet is in TO-DO list and might looks exactly as separated nodes.
