### ISSUE TITLE
.tox doesn't import in the latest version of TD

### ISSUE THREAD

**Issue by gnmorfu** [olegchomp/TDDiffusionAPI#4]
I drag and drop it in the project and just does nothing.
If I open it separately, still doesn't do it properly.

**Comment by davinel000** [comment]
Have you tried to download it not as a separate file, but within an archive (Code -> Download ZIP)? In my case, it helped to get the importable .tox

**Comment by olegchomp** [comment]
> I drag and drop it in the project and just does nothing. If I open it separately, still doesn't do it properly.

Try to download from releases page.
https://github.com/olegchomp/TDDiffusionAPI/releases

**Comment by gnmorfu** [comment]
Aaaah that dit it! Thank you!
