### ISSUE TITLE
Seeds above 2147483647, are not accepted.

### ISSUE THREAD

**Issue by dichbg** [olegchomp/TDDiffusionAPI#8]
Seed parameter does not need to be an integer, it can be a string.

"seed": int(self.tda.par.T2isd) if self.tda.par.Srandomseed == False else self.randomseed(), can be replaced with:
"seed": str(self.tda.par.T2isd),

You don't really need a random seed function, as you can supply -1 as seed input and use the built in auto1111 function.

Thank you for this contribution, this tox file is amazing!

**Comment by olegchomp** [comment]
fixed
